/** Declaration file generated by dts-gen */

import { Soal } from "lib/types";

export const conditionKeys: string[];

export const itemKeys: string[];

export const leaders: string[];

export const version: string;

export function createSequence(): string[];

export function getCondition(key: string): string;

// export function getItem(key: any): {
//   kondisi: string
//   soal: string
//   faktor: string
//   pilihan: { key: string, html: string }[]
// } | null;
export function getItem(key: string): Soal

export function groupedKeys(): {
  K01: string[]
  K02: string[]
  K03: string[]
  K04: string[]
  K05: string[]
  K06: string[]
  K07: string[]
  K08: string[]
  K09: string[]
  K10: string[]
  K11: string[]
  K12: string[]
  K13: string[]
  K14: string[]
  K15: string[]
  K16: string[]
  K17: string[]
  K18: string[]
  K19: string[]
  K20: string[]
  K21: string[]
  K22: string[]
  K23: string[]
  K24: string[]
  K25: string[]
  K26: string[]
};

export function orderedItems(): { type: string, key: string }[];

